export const ORDER_BY = {
  CHARACTERS: {
    name: 'name',
    modified: 'modified',
    nameDescending: '-name',
    modifiedDescending: '-modified',
  },
  COMICS: {
    focDate: 'focDate',
    onSaleDate: 'onsaleDate',
    title: 'title',
    issueNumber: 'issueNumber',
    modified: 'modified',
    focDateDescending: '-focDate',
    onSaleDateDescending: '-onsaleDate',
    titleDescending: '-title',
    issueNumberDescending: '-issueNumber',
    modifiedDescending: '-modified',
  },
  CREATORS: {
    firstName: 'firstName',
    middleName: 'middleName',
    lastName: 'lastName',
    suffix: 'suffix',
    modified: 'modified',
    firstNameDescending: '-firstName',
    middleNameDescending: '-middleName',
    lastNameDescending: '-lastName',
    suffixDescending: '-suffix',
    modifiedDescending: '-modified',
  },
  EVENTS: {
    name: 'name',
    startDate: 'startDate',
    modified: 'modified',
    nameDescending: '-name',
    startDateDescending: '-startDate',
    modifiedDescending: '-modified',
  },
  SERIES: {
    title: 'title',
    modified: 'modified',
    startYear: 'startYear',
    titleDescending: '-title',
    modifiedDescending: '-modified',
    startYearDescending: '-startYear',
  },
  STORIES: {
    id: 'id',
    modified: 'modified',
    idDescending: '-id',
    modifiedDescending: '-modified',
  },
} as const

export const MarvelImageVariants = {
  portraitSmall: 'portrait_small',
  portraitMedium: 'portrait_medium',
  portraitXLarge: 'portrait_xlarge',
  portraitFantastic: 'portrait_fantastic',
  portraitUncanny: 'portrait_uncanny',
  portraitIncredible: 'portrait_incredible',
  standardSmall: 'standard_small',
  standardMedium: 'standard_medium',
  standardLarge: 'standard_large',
  standardXLarge: 'standard_xlarge',
  standardFantastic: 'standard_fantastic',
  standardAmazing: 'standard_amazing',
  landscapeSmall: 'landscape_small',
  landscapeMedium: 'landscape_medium',
  landscapeLarge: 'landscape_large',
  landscapeXLarge: 'landscape_xlarge',
  landscapeAmazing: 'landscape_amazing',
  landscapeIncredible: 'landscape_incredible',
  detail: 'detail',
  fullSize: 'full-size',
} as const
